pimcore:
    objects:
        custom_layouts:
            definitions:
                c7c2ff44-8a39-49d1-907a-41f4db0d5787:
                    id: c7c2ff44-8a39-49d1-907a-41f4db0d5787
                    name: wholesaleAndRetail
                    description: ''
                    creationDate: 1701640183
                    modificationDate: 1702021304
                    userOwner: 2
                    classId: Brand
                    layoutDefinitions:
                        name: pimcore_root
                        type: null
                        region: null
                        title: null
                        width: 0
                        height: 0
                        collapsible: false
                        collapsed: false
                        bodyStyle: null
                        datatype: layout
                        children:
                            -
                                name: 'Brand Information'
                                type: null
                                region: null
                                title: 'Brand Information'
                                width: ''
                                height: ''
                                collapsible: false
                                collapsed: false
                                bodyStyle: ''
                                datatype: layout
                                children:
                                    -
                                        name: BrandName
                                        title: 'Brand Name'
                                        tooltip: 'Name of the Brand'
                                        mandatory: true
                                        noteditable: true
                                        index: false
                                        locked: false
                                        style: ''
                                        permissions: null
                                        fieldtype: input
                                        relationType: false
                                        invisible: false
                                        visibleGridView: true
                                        visibleSearch: false
                                        defaultValue: null
                                        columnLength: 190
                                        regex: ''
                                        regexFlags: {  }
                                        unique: true
                                        showCharCount: false
                                        width: ''
                                        defaultValueGenerator: ''
                                        datatype: data
                                    -
                                        name: brandLogo
                                        title: 'Brand Logo'
                                        tooltip: ''
                                        mandatory: true
                                        noteditable: true
                                        index: false
                                        locked: false
                                        style: ''
                                        permissions: null
                                        fieldtype: image
                                        relationType: false
                                        invisible: false
                                        visibleGridView: true
                                        visibleSearch: false
                                        uploadPath: ''
                                        width: ''
                                        height: ''
                                        datatype: data
                                    -
                                        name: brandDescription
                                        title: 'Brand Description'
                                        tooltip: ''
                                        mandatory: false
                                        noteditable: true
                                        index: false
                                        locked: false
                                        style: ''
                                        permissions: null
                                        fieldtype: textarea
                                        relationType: false
                                        invisible: false
                                        visibleGridView: true
                                        visibleSearch: false
                                        maxLength: null
                                        showCharCount: false
                                        excludeFromSearchIndex: false
                                        height: ''
                                        width: ''
                                        datatype: data
                                    -
                                        name: countryOfOrgin
                                        title: 'Country Of Orgin'
                                        tooltip: ''
                                        mandatory: false
                                        noteditable: true
                                        index: false
                                        locked: false
                                        style: ''
                                        permissions: null
                                        fieldtype: country
                                        relationType: false
                                        invisible: false
                                        visibleGridView: true
                                        visibleSearch: false
                                        options: null
                                        defaultValue: null
                                        columnLength: 190
                                        dynamicOptions: false
                                        defaultValueGenerator: ''
                                        width: ''
                                        optionsProviderType: null
                                        optionsProviderClass: null
                                        optionsProviderData: null
                                        restrictTo: ''
                                        datatype: data
                                locked: false
                                fieldtype: panel
                                layout: null
                                border: false
                                icon: /bundles/pimcoreadmin/img/twemoji/1f6e1.svg
                                labelWidth: 100
                                labelAlign: left
                        locked: false
                        fieldtype: panel
                        layout: null
                        border: false
                        icon: null
                        labelWidth: 100
                        labelAlign: left
                    default: 0
