pimcore_custom_reports:
    definitions:
        Workflow:
            name: Workflow
            sql: ''
            dataSourceConfig:
                -
                    sql: 'count(place), place'
                    from: element_workflow_state
                    where: ''
                    groupby: place
                    type: sql
            columnConfiguration:
                -
                    name: count(place)
                    display: true
                    export: true
                    order: true
                    width: ''
                    label: ''
                    id: extModel1369-5
                -
                    name: place
                    display: true
                    export: true
                    order: true
                    width: ''
                    label: ''
                    id: extModel1369-6
            niceName: 'Worflow Custom Report'
            group: Workflow
            groupIconClass: ''
            iconClass: ''
            menuShortcut: true
            reportClass: ''
            chartType: pie
            pieColumn: count(place)
            pieLabelColumn: place
            xAxis: null
            yAxis: {  }
            modificationDate: 1701760640
            creationDate: 1701759580
            shareGlobally: true
            sharedUserNames: {  }
            sharedRoleNames: {  }
